#!/usr/bin/env python3
"""
Automatic setup script for Famousify Load Tester V2
Handles installation, configuration, and initial setup
"""

import os
import sys
import subprocess
from pathlib import Path

def print_header(text):
    """Print formatted header"""
    print("\n" + "="*70)
    print(f"  {text}")
    print("="*70 + "\n")

def check_python_version():
    """Verify Python version"""
    print("🐍 Checking Python version...")
    
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print(f"❌ Python 3.8+ required, found {version.major}.{version.minor}")
        return False
    
    print(f"✅ Python {version.major}.{version.minor}.{version.micro}")
    return True

def install_dependencies():
    """Install required packages"""
    print("\n📦 Installing dependencies...")
    
    requirements_file = Path("requirements.txt")
    
    if not requirements_file.exists():
        print("⚠️  requirements.txt not found, creating minimal version...")
        requirements_file.write_text("""aiohttp==3.9.1
aiofiles==23.2.1
requests==2.31.0
""")
    
    try:
        subprocess.check_call([
            sys.executable, "-m", "pip", "install", "-r", "requirements.txt"
        ])
        print("✅ Dependencies installed")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to install dependencies")
        return False

def create_config():
    """Create .env configuration file"""
    print("\n⚙️  Creating configuration...")
    
    env_file = Path(".env")
    env_example = Path(".env.example")
    
    if env_file.exists():
        print("ℹ️  .env file already exists")
        overwrite = input("Overwrite? (yes/no): ")
        if overwrite.lower() not in ['yes', 'y']:
            print("Keeping existing .env")
            return True
    
    # Get configuration from user
    print("\n📝 Configuration Setup")
    print("-" * 70)
    
    base_url = input("Base URL [https://web-production-abb48.up.railway.app]: ").strip()
    if not base_url:
        base_url = "https://web-production-abb48.up.railway.app"
    
    admin_token = input("Admin Token [famousify-admin-2025]: ").strip()
    if not admin_token:
        admin_token = "famousify-admin-2025"
    
    test_image = input("Test Image URL [default Unsplash]: ").strip()
    if not test_image:
        test_image = "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800"
    
    # Write config
    config_content = f"""# Famousify Load Tester V2 Configuration
# Generated by setup.py

FAMOUSIFY_BASE_URL={base_url}
FAMOUSIFY_ADMIN_TOKEN={admin_token}
FAMOUSIFY_TEST_IMAGE_URL={test_image}
FAMOUSIFY_TIMEOUT=180
FAMOUSIFY_POLL_INTERVAL=5
"""
    
    env_file.write_text(config_content)
    print("\n✅ Configuration saved to .env")
    return True

def create_directories():
    """Create necessary directories"""
    print("\n📁 Creating directories...")
    
    dirs = [
        Path("results"),
        Path("results/reports"),
        Path("results/images"),
    ]
    
    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)
        print(f"  ✅ {dir_path}/")
    
    return True

def test_installation():
    """Test if installation works"""
    print("\n🧪 Testing installation...")
    
    try:
        # Try importing main modules
        import aiohttp
        import asyncio
        
        print("✅ Core modules working")
        
        # Try importing GUI (optional)
        try:
            import tkinter
            print("✅ GUI available")
        except ImportError:
            print("⚠️  GUI not available (tkinter missing) - CLI mode only")
        
        return True
    except ImportError as e:
        print(f"❌ Import failed: {e}")
        return False

def print_next_steps():
    """Print what to do next"""
    print_header("🎉 SETUP COMPLETE!")
    
    print("Next steps:\n")
    print("1. Review configuration:")
    print("   - Edit .env file if needed")
    print("   - Or configure via GUI\n")
    
    print("2. Run the load tester:")
    print("   GUI mode:  python famousify_load_tester_v2.py")
    print("   CLI mode:  python famousify_load_tester_v2.py --cli\n")
    
    print("3. Quick test:")
    print("   - Start with 3-5 requests")
    print("   - Verify system responds correctly")
    print("   - Check results/ folder\n")
    
    print("4. Build standalone EXE (optional):")
    print("   python build_exe.py\n")
    
    print("📚 For full documentation, see README.md")
    print()

def main():
    """Main setup flow"""
    print_header("🚀 FAMOUSIFY LOAD TESTER V2 - SETUP")
    
    print("This script will:")
    print("  • Check Python version")
    print("  • Install dependencies")
    print("  • Create configuration")
    print("  • Set up directory structure")
    print("  • Test installation")
    print()
    
    proceed = input("Continue? (yes/no): ")
    if proceed.lower() not in ['yes', 'y']:
        print("Setup cancelled")
        return
    
    # Run setup steps
    steps = [
        ("Python Version", check_python_version),
        ("Dependencies", install_dependencies),
        ("Configuration", create_config),
        ("Directories", create_directories),
        ("Installation Test", test_installation),
    ]
    
    failed_steps = []
    
    for step_name, step_func in steps:
        print_header(step_name)
        
        try:
            success = step_func()
            if not success:
                failed_steps.append(step_name)
        except Exception as e:
            print(f"❌ Error: {e}")
            failed_steps.append(step_name)
    
    # Summary
    if failed_steps:
        print_header("⚠️  SETUP COMPLETED WITH WARNINGS")
        print("Failed steps:")
        for step in failed_steps:
            print(f"  ❌ {step}")
        print("\nYou may need to fix these manually.")
    else:
        print_next_steps()
    
    print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏹️  Setup interrupted")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Unexpected error: {e}")
        sys.exit(1)
